version: '3.8'

services:

  simple-web-service-compose:
    image: devopsdockeruh/simple-web-service
    build: .
    container_name: simple-web-service-compose
    ports:
      - 127.0.0.1:8080:8080
    command: server