version: '3.8'

services:
  backend:
    build:
      context: ./example-backend
    container_name: example-backend
    ports:
      - "127.0.0.1:8080:8080"
    environment:
      PORT: 8080
      REQUEST_ORIGIN: http://localhost:5000

  frontend:
    build:
      context: ./example-frontend
    container_name: example-frontend
    ports:
      - "127.0.0.1:5000:5000"
    environment:
      REACT_APP_BACKEND_URL: http://backend:8080
    depends_on:
      - backend
